### ISSUE TITLE
Requesting help in Ambiguity function

### ISSUE THREAD

**Issue by manasdas17** [ryanvolz/thesis#1]
Hi,
   This is Manas from IIT-Bomaby,India.I came across your thesis on radar and relevant codes.It has been a great piece of work and a great help to me as i am working on the sidelobe reduction techniques for pulse compression radar and its python implementation.I have implemented python code for ambiguity function but not getting desired results.Could you plz have a look at my code if i share it with you.Plz let me know.My mailid is manasdas17@gmail.com. Could i have yours?

Thanks & Regards,
Manas

**Comment by ryanvolz** [comment]
For calculating the ambiguity function, you can compare to my code at https://github.com/ryanvolz/echolect/blob/master/echolect/core/coding.py and https://github.com/ryanvolz/echolect/tree/master/echolect/filtering. That calculation goes through a number of functions, so it might not be very straightforward to figure out what's going on. I could look at your code if you post it to Github and let me know, otherwise my email address is ryan.volz@gmail.com. Cheers!

**Comment by ryanvolz** [comment]
I created a simplified function for calculating the ambiguity, and you can view it in this IPython notebook: http://nbviewer.ipython.org/gist/ryanvolz/8b0d9f3e48ec8ddcef4d. You can try to adapt this and expand on it to suit your needs.

**Comment by manasdas17** [comment]
Thanks.I am trying to get 3-D plot instead of an image.But couldn't get
from your code.
Could you plz modify the code to get a 3-D plot .

Regards,
Manas

**Comment by ryanvolz** [comment]
Try mplot3d to make a contour or wireframe plot like in your original script. This will work exactly the same with the ambiguity function I've computed.

**Comment by manasdas17** [comment]
but everytime i have to append some zeros to the L  - axis to make the dimension equal for plotting for wireframe.how to overcome this?i am trying to plot for a LFM signal.

**Comment by ryanvolz** [comment]
You can plot a wireframe by creating 1-D indices for delay (x) and frequency shift (y), then turning them into 2-D indices that match the size of the ambiguity function by using numpy's meshgrid function (X, Y = meshgrid(x,y)).
